#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantCompliance(CisoAssistantApiBase):
    def api_applied_controls_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/",
            path_params=[],
            query_params=[
                "assets",
                "category",
                "compliance_assessments",
                "control_impact",
                "csf_function",
                "effort",
                "eta",
                "eta__gt",
                "eta__gte",
                "eta__lt",
                "eta__lte",
                "eta__month",
                "eta__year",
                "evidences",
                "filtering_labels",
                "findings",
                "findings_assessments",
                "folder",
                "genericcollection",
                "id",
                "incidents",
                "is_assigned",
                "limit",
                "linked_models",
                "name",
                "objectives",
                "offset",
                "ordering",
                "owner",
                "priority",
                "processings",
                "progress_field",
                "ref_id",
                "reference_control",
                "requirement_assessments",
                "risk_assessments",
                "risk_scenarios",
                "risk_scenarios_e",
                "search",
                "security_exceptions",
                "stakeholders",
                "status",
                "to_review",
                "todo",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_applied_controls_create(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/applied-controls/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_update(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/applied-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/applied-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_destroy(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/applied-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_duplicate_create(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/applied-controls/{id}/duplicate/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_sync_to_reference_control_create(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/applied-controls/{id}/sync-to-reference-control/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_analytics_retrieve(self, **kwargs) -> Response:
        """Aggregated analytics over the filtered applied-controls queryset."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/analytics/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_autocomplete_retrieve(self, **kwargs) -> Response:
        """Minimal endpoint for autocomplete selects."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/autocomplete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/applied-controls/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_category_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/category/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_control_impact_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/control_impact/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_csf_function_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/csf_function/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_effort_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/effort/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_export_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/export_csv/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_export_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/export_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_get_controls_info_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/get_controls_info/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_get_gantt_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/get_gantt_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_get_timeline_info_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/get_timeline_info/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_ids_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/ids/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_impact_effort_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/impact_effort/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_impact_graph_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/impact_graph/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_linked_models_retrieve(self, **kwargs) -> Response:
        """Return available model types that can be linked to applied controls"""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/linked_models/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_merge_create(self, **kwargs) -> Response:
        """Merge N source applied controls into 1 target. See"""
        return self._call(
            http="POST",
            url_template="/api/applied-controls/merge/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_mss_xlsx_retrieve(self, **kwargs) -> Response:
        """Export filtered applied controls in ANSSI MonServiceSécurisé format"""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/mss_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_owner_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/owner/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_per_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/per_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_priority_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/priority/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_priority_chart_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/priority_chart_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_sunburst_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/sunburst_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_to_review_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/to_review/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_todo_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/todo/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_applied_controls_updatables_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/applied-controls/updatables/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/",
            path_params=[],
            query_params=[
                "assets",
                "authors",
                "campaign",
                "ebios_rm_studies",
                "evidences",
                "folder",
                "framework",
                "genericcollection",
                "id",
                "limit",
                "name",
                "offset",
                "ordering",
                "perimeter",
                "ref_id",
                "reviewers",
                "search",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_compliance_assessments_create(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_update(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/compliance-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/compliance-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_destroy(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/compliance-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_action_plan_list(self, **kwargs) -> Response:
        """api_compliance_assessments_action_plan_list"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/action-plan/",
            path_params=["id"],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_compliance_assessments_action_plan_budget_overview_list(
        self, **kwargs
    ) -> Response:
        """Mixin that computes budget aggregation over an applied controls queryset."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/action-plan/budget-overview/",
            path_params=["id"],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_compliance_assessments_action_plan_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/action_plan_csv/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_action_plan_pdf_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/action_plan_pdf/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_action_plan_xlsx_retrieve(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/action_plan_xlsx/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_combined_tree_retrieve(self, **kwargs) -> Response:
        """Requirement tree with domain-tree inheritance applied as an overlay."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/combined_tree/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_comparable_audits_retrieve(
        self, **kwargs
    ) -> Response:
        """Get list of compliance assessments that can be compared with this one"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/comparable_audits/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_compare_retrieve(self, **kwargs) -> Response:
        """Compare two compliance assessments that use the same framework"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/compare/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_compliance_assessment_csv_retrieve(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/compliance_assessment_csv/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_compliance_timeline_retrieve(
        self, **kwargs
    ) -> Response:
        """Returns compliance metrics over time from HistoricalMetric snapshots."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/compliance_timeline/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_controls_coverage_retrieve(
        self, **kwargs
    ) -> Response:
        """Controls coverage analysis for this compliance assessment."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/controls_coverage/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_cyfun_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/cyfun_xlsx/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_donut_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/donut_data/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_evidence_coverage_retrieve(
        self, **kwargs
    ) -> Response:
        """Evidence coverage analysis — direct (on RA) and indirect (via applied controls)."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/evidence_coverage/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_evidences_list_list(self, **kwargs) -> Response:
        """api_compliance_assessments_evidences_list_list"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/evidences-list/",
            path_params=["id"],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_compliance_assessments_exceptions_summary_retrieve(
        self, **kwargs
    ) -> Response:
        """Security exceptions summary for this compliance assessment."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/exceptions_summary/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_export_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/export/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_frameworks_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/frameworks/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_global_score_retrieve(self, **kwargs) -> Response:
        """Returns the global score of the compliance assessment"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/global_score/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_implementation_groups_breakdown_retrieve(
        self, **kwargs
    ) -> Response:
        """Breakdown of compliance results by implementation group."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/implementation_groups_breakdown/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_is_auditee_retrieve(self, **kwargs) -> Response:
        """Returns whether the current user is an auditee for this compliance assessment."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/is-auditee/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_mailing_create(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/{id}/mailing/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_map_from_create(self, **kwargs) -> Response:
        """Map data from a source audit into this one."""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/{id}/map_from/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_map_from_preview_retrieve(
        self, **kwargs
    ) -> Response:
        """Preview the effect of mapping data from a source audit into this one."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/map_from_preview/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_progress_ts_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/progress_ts/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_quality_check_retrieve_2(self, **kwargs) -> Response:
        """Returns the quality check of a specific assessment"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/quality_check/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_requirements_list_retrieve(
        self, **kwargs
    ) -> Response:
        """Returns the list of requirement assessments for the different audit modes"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/requirements_list/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_section_compliance_retrieve(
        self, **kwargs
    ) -> Response:
        """Aggregates compliance results and scores per top-level requirement group."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/section_compliance/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_soa_retrieve(self, **kwargs) -> Response:
        """Returns the requirement tree enriched with applied controls and"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/soa/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_suggestions_applied_controls_retrieve(
        self, **kwargs
    ) -> Response:
        """api_compliance_assessments_suggestions_applied_controls_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/suggestions/applied-controls/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_suggestions_applied_controls_create(
        self, **kwargs
    ) -> Response:
        """api_compliance_assessments_suggestions_applied_controls_create"""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/{id}/suggestions/applied-controls/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_sync_to_actions_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/syncToActions/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_sync_to_actions_create(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/{id}/syncToActions/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_threats_metrics_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/threats_metrics/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_tree_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/tree/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_update_requirement_create(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/{id}/update_requirement/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_word_report_retrieve(self, **kwargs) -> Response:
        """Word report generation (Exec)"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/word_report/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/{id}/xlsx/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_analytics_retrieve(self, **kwargs) -> Response:
        """Returns compliance analytics data grouped by framework and domain"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/analytics/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_auditee_dashboard_retrieve(
        self, **kwargs
    ) -> Response:
        """Returns per-assignment progress data for the auditee's dashboard."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/auditee-dashboard/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/compliance-assessments/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_per_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/per_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_quality_check_retrieve(self, **kwargs) -> Response:
        """Returns the quality check of every compliance assessment"""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/quality_check/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_recap_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/recap/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_score_calculation_method_retrieve(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/score_calculation_method/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_compliance_assessments_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows compliance assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/compliance-assessments/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_mapping_libraries_list(self, **kwargs) -> Response:
        """api_mapping_libraries_list"""
        return self._call(
            http="GET",
            url_template="/api/mapping-libraries/",
            path_params=[],
            query_params=[
                "limit",
                "locale",
                "offset",
                "ordering",
                "packager",
                "provider",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_policies_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/policies/",
            path_params=[],
            query_params=[
                "assets",
                "category",
                "compliance_assessments",
                "control_impact",
                "csf_function",
                "effort",
                "eta",
                "eta__gt",
                "eta__gte",
                "eta__lt",
                "eta__lte",
                "eta__month",
                "eta__year",
                "evidences",
                "filtering_labels",
                "findings",
                "findings_assessments",
                "folder",
                "genericcollection",
                "id",
                "incidents",
                "is_assigned",
                "limit",
                "linked_models",
                "name",
                "objectives",
                "offset",
                "ordering",
                "owner",
                "priority",
                "processings",
                "progress_field",
                "ref_id",
                "reference_control",
                "requirement_assessments",
                "risk_assessments",
                "risk_scenarios",
                "risk_scenarios_e",
                "search",
                "security_exceptions",
                "stakeholders",
                "status",
                "to_review",
                "todo",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_policies_create(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/policies/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/policies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_update(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/policies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/policies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_destroy(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/policies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/policies/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_duplicate_create(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/policies/{id}/duplicate/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_sync_to_reference_control_create(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/policies/{id}/sync-to-reference-control/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_analytics_retrieve(self, **kwargs) -> Response:
        """Aggregated analytics over the filtered applied-controls queryset."""
        return self._call(
            http="GET",
            url_template="/api/policies/analytics/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_autocomplete_retrieve(self, **kwargs) -> Response:
        """Minimal endpoint for autocomplete selects."""
        return self._call(
            http="GET",
            url_template="/api/policies/autocomplete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/policies/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_category_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/category/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_control_impact_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/control_impact/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_csf_function_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/csf_function/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_effort_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/effort/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_export_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/export_csv/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_export_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/export_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_get_controls_info_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/get_controls_info/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_get_gantt_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/get_gantt_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_get_timeline_info_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/get_timeline_info/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_ids_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/ids/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_impact_effort_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/impact_effort/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_impact_graph_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/impact_graph/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_linked_models_retrieve(self, **kwargs) -> Response:
        """Return available model types that can be linked to applied controls"""
        return self._call(
            http="GET",
            url_template="/api/policies/linked_models/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_merge_create(self, **kwargs) -> Response:
        """Merge N source applied controls into 1 target. See"""
        return self._call(
            http="POST",
            url_template="/api/policies/merge/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_mss_xlsx_retrieve(self, **kwargs) -> Response:
        """Export filtered applied controls in ANSSI MonServiceSécurisé format"""
        return self._call(
            http="GET",
            url_template="/api/policies/mss_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_owner_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/owner/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_per_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/per_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_priority_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/priority/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_priority_chart_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/priority_chart_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_sunburst_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/sunburst_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_to_review_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/to_review/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_todo_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/todo/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_policies_updatables_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows applied controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/policies/updatables/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/",
            path_params=[],
            query_params=[
                "category",
                "csf_function",
                "filtering_labels",
                "findings",
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
                "urn",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_reference_controls_create(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/reference-controls/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_update(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/reference-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/reference-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_destroy(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/reference-controls/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_sync_applied_controls_create(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/reference-controls/{id}/sync-applied-controls/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_syncable_applied_controls_retrieve(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/{id}/syncable-applied-controls/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/reference-controls/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_category_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/category/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_csf_function_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/csf_function/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_reference_controls_provider_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows reference controls to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/reference-controls/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/",
            path_params=[],
            query_params=[
                "applied_controls",
                "compliance_assessment",
                "compliance_assessment__assets__ref_id",
                "compliance_assessment__perimeter",
                "compliance_assessment__perimeter__name",
                "compliance_assessment__ref_id",
                "evidences",
                "extended_result",
                "folder",
                "folder__name",
                "id",
                "limit",
                "offset",
                "ordering",
                "requirement__assessable",
                "requirement__urn",
                "result",
                "search",
                "security_exceptions",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_requirement_assessments_create(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/requirement-assessments/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_update(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/requirement-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/requirement-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_destroy(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/requirement-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_suggestions_applied_controls_retrieve(
        self, **kwargs
    ) -> Response:
        """api_requirement_assessments_suggestions_applied_controls_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/{id}/suggestions/applied-controls/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_suggestions_applied_controls_create(
        self, **kwargs
    ) -> Response:
        """api_requirement_assessments_suggestions_applied_controls_create"""
        return self._call(
            http="POST",
            url_template="/api/requirement-assessments/{id}/suggestions/applied-controls/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/requirement-assessments/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_extended_result_retrieve(
        self, **kwargs
    ) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/extended_result/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_per_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/per_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_result_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/result/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_to_review_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/to_review/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_todo_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/todo/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assessments_updatables_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assessments/updatables/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assignments/",
            path_params=[],
            query_params=[
                "actor",
                "compliance_assessment",
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "search",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_requirement_assignments_create(self, **kwargs) -> Response:
        """API endpoint that allows requirement assignments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/requirement-assignments/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_update(self, **kwargs) -> Response:
        """API endpoint that allows requirement assignments to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/requirement-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows requirement assignments to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/requirement-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_destroy(self, **kwargs) -> Response:
        """API endpoint that allows requirement assignments to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/requirement-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/requirement-assignments/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirement assignments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assignments/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_requirements_list_retrieve(
        self, **kwargs
    ) -> Response:
        """Returns the scoped requirements list for this assignment."""
        return self._call(
            http="GET",
            url_template="/api/requirement-assignments/{id}/requirements_list/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_set_status_create(self, **kwargs) -> Response:
        """Transition assignment to a new status."""
        return self._call(
            http="POST",
            url_template="/api/requirement-assignments/{id}/set_status/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_assignments_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/requirement-assignments/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/",
            path_params=[],
            query_params=["id", "limit", "offset", "ordering", "provider", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_create(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_create"""
        return self._call(
            http="POST",
            url_template="/api/requirement-mapping-sets/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_update(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_update"""
        return self._call(
            http="PUT",
            url_template="/api/requirement-mapping-sets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_partial_update(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/requirement-mapping-sets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_destroy(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/requirement-mapping-sets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_graph_data_retrieve_2(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_graph_data_retrieve_2"""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/{id}/graph_data/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_object_retrieve(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/requirement-mapping-sets/batch-action/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_graph_data_retrieve(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_graph_data_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/graph-data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_mapping_sets_provider_retrieve(self, **kwargs) -> Response:
        """api_requirement_mapping_sets_provider_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/requirement-mapping-sets/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/requirement-nodes/",
            path_params=[],
            query_params=[
                "framework",
                "id",
                "limit",
                "offset",
                "ordering",
                "search",
                "urn",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_requirement_nodes_create(self, **kwargs) -> Response:
        """API endpoint that allows requirements to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/requirement-nodes/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/requirement-nodes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_update(self, **kwargs) -> Response:
        """API endpoint that allows requirements to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/requirement-nodes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows requirements to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/requirement-nodes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_destroy(self, **kwargs) -> Response:
        """API endpoint that allows requirements to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/requirement-nodes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/requirement-nodes/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_inspect_requirement_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirements to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-nodes/{id}/inspect_requirement/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows requirements to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/requirement-nodes/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_serve_image_retrieve(self, **kwargs) -> Response:
        """Serve an image attachment belonging to this requirement node."""
        return self._call(
            http="GET",
            url_template="/api/requirement-nodes/{id}/serve-image/{attachment_id}/",
            path_params=["attachment_id", "id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_upload_image_create(self, **kwargs) -> Response:
        """Upload an image file and attach it to this requirement node."""
        return self._call(
            http="POST",
            url_template="/api/requirement-nodes/{id}/upload-image/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_requirement_nodes_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/requirement-nodes/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
