#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantAuthUsers(CisoAssistantApiBase):
    def api_accounts_saml_download_cert_retrieve(self, **kwargs) -> Response:
        """api_accounts_saml_download_cert_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/accounts/saml/{organization_slug}/download-cert/",
            path_params=["organization_slug"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_accounts_saml_generate_keys_create(self, **kwargs) -> Response:
        """Endpoint to generate a key pair (private key + self-signed X.509 certificate)."""
        return self._call(
            http="POST",
            url_template="/api/accounts/saml/{organization_slug}/generate-keys/",
            path_params=["organization_slug"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_csrf_retrieve(self, **kwargs) -> Response:
        """API endpoint that returns the CSRF token."""
        return self._call(
            http="GET",
            url_template="/api/csrf/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_auth_tokens_retrieve(self, **kwargs) -> Response:
        """Get all personal access tokens for the user."""
        return self._call(
            http="GET",
            url_template="/api/iam/auth-tokens/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_auth_tokens_create(self, **kwargs) -> Response:
        """api_iam_auth_tokens_create"""
        return self._call(
            http="POST",
            url_template="/api/iam/auth-tokens/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_auth_tokens_destroy(self, **kwargs) -> Response:
        """api_iam_auth_tokens_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/iam/auth-tokens/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_change_password_create(self, **kwargs) -> Response:
        """An endpoint for changing password."""
        return self._call(
            http="POST",
            url_template="/api/iam/change-password/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_current_user_retrieve(self, **kwargs) -> Response:
        """api_iam_current_user_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/iam/current-user/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_login_create(self, **kwargs) -> Response:
        """api_iam_login_create"""
        return self._call(
            http="POST",
            url_template="/api/iam/login/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_logout_create(self, **kwargs) -> Response:
        """api_iam_logout_create"""
        return self._call(
            http="POST",
            url_template="/api/iam/logout/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_logoutall_create(self, **kwargs) -> Response:
        """Log the user out of all sessions"""
        return self._call(
            http="POST",
            url_template="/api/iam/logoutall/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_password_reset_create(self, **kwargs) -> Response:
        """api_iam_password_reset_create"""
        return self._call(
            http="POST",
            url_template="/api/iam/password-reset/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_password_reset_confirm_create(self, **kwargs) -> Response:
        """API Endpoint for reset password confirm"""
        return self._call(
            http="POST",
            url_template="/api/iam/password-reset/confirm/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_revoke_sessions_create(self, **kwargs) -> Response:
        """An endpoint for revoking all other user sessions (except the current one)."""
        return self._call(
            http="POST",
            url_template="/api/iam/revoke-sessions/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_session_token_create(self, **kwargs) -> Response:
        """API Endpoint for getting the session token from an access token"""
        return self._call(
            http="POST",
            url_template="/api/iam/session-token/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_iam_set_password_create(self, **kwargs) -> Response:
        """An endpoint for setting a password as an administrator."""
        return self._call(
            http="POST",
            url_template="/api/iam/set-password/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/role-assignments/",
            path_params=[],
            query_params=["folder", "id", "limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_role_assignments_create(self, **kwargs) -> Response:
        """API endpoint that allows role assignments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/role-assignments/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/role-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_update(self, **kwargs) -> Response:
        """API endpoint that allows role assignments to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/role-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows role assignments to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/role-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_destroy(self, **kwargs) -> Response:
        """API endpoint that allows role assignments to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/role-assignments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/role-assignments/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows role assignments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/role-assignments/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_role_assignments_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/role-assignments/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/teams/",
            path_params=[],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_teams_create(self, **kwargs) -> Response:
        """api_teams_create"""
        return self._call(
            http="POST",
            url_template="/api/teams/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/teams/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_update(self, **kwargs) -> Response:
        """api_teams_update"""
        return self._call(
            http="PUT",
            url_template="/api/teams/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_partial_update(self, **kwargs) -> Response:
        """api_teams_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/teams/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_destroy(self, **kwargs) -> Response:
        """api_teams_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/teams/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/teams/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_object_retrieve(self, **kwargs) -> Response:
        """api_teams_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/teams/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_teams_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/teams/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/user-groups/",
            path_params=[],
            query_params=["folder", "id", "limit", "offset", "ordering"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_user_groups_create(self, **kwargs) -> Response:
        """API endpoint that allows user groups to be viewed or edited"""
        return self._call(
            http="POST",
            url_template="/api/user-groups/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/user-groups/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_update(self, **kwargs) -> Response:
        """API endpoint that allows user groups to be viewed or edited"""
        return self._call(
            http="PUT",
            url_template="/api/user-groups/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows user groups to be viewed or edited"""
        return self._call(
            http="PATCH",
            url_template="/api/user-groups/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_destroy(self, **kwargs) -> Response:
        """API endpoint that allows user groups to be viewed or edited"""
        return self._call(
            http="DELETE",
            url_template="/api/user-groups/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/user-groups/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows user groups to be viewed or edited"""
        return self._call(
            http="GET",
            url_template="/api/user-groups/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_groups_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/user-groups/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_preferences_retrieve(self, **kwargs) -> Response:
        """api_user_preferences_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/user-preferences/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_user_preferences_partial_update(self, **kwargs) -> Response:
        """api_user_preferences_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/user-preferences/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/users/",
            path_params=[],
            query_params=[
                "email",
                "exclude_current",
                "expiry_date",
                "first_name",
                "id",
                "is_active",
                "is_applied_control_owner",
                "is_approver",
                "is_third_party",
                "keep_local_login",
                "last_name",
                "limit",
                "offset",
                "ordering",
                "representative__entity",
                "search",
                "user_groups",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_users_create(self, **kwargs) -> Response:
        """API endpoint that allows users to be viewed or edited"""
        return self._call(
            http="POST",
            url_template="/api/users/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/users/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_update(self, **kwargs) -> Response:
        """API endpoint that allows users to be viewed or edited"""
        return self._call(
            http="PUT",
            url_template="/api/users/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows users to be viewed or edited"""
        return self._call(
            http="PATCH",
            url_template="/api/users/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_destroy(self, **kwargs) -> Response:
        """API endpoint that allows users to be viewed or edited"""
        return self._call(
            http="DELETE",
            url_template="/api/users/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/users/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows users to be viewed or edited"""
        return self._call(
            http="GET",
            url_template="/api/users/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_users_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/users/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
