#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantAssets(CisoAssistantApiBase):
    def api_asset_capabilities_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/asset-capabilities/",
            path_params=[],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_asset_capabilities_create(self, **kwargs) -> Response:
        """api_asset_capabilities_create"""
        return self._call(
            http="POST",
            url_template="/api/asset-capabilities/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/asset-capabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_update(self, **kwargs) -> Response:
        """api_asset_capabilities_update"""
        return self._call(
            http="PUT",
            url_template="/api/asset-capabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_partial_update(self, **kwargs) -> Response:
        """api_asset_capabilities_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/asset-capabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_destroy(self, **kwargs) -> Response:
        """api_asset_capabilities_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/asset-capabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/asset-capabilities/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_object_retrieve(self, **kwargs) -> Response:
        """api_asset_capabilities_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/asset-capabilities/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_capabilities_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/asset-capabilities/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/asset-class/",
            path_params=[],
            query_params=[
                "id",
                "limit",
                "name",
                "offset",
                "ordering",
                "parent",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_asset_class_create(self, **kwargs) -> Response:
        """api_asset_class_create"""
        return self._call(
            http="POST",
            url_template="/api/asset-class/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/asset-class/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_update(self, **kwargs) -> Response:
        """api_asset_class_update"""
        return self._call(
            http="PUT",
            url_template="/api/asset-class/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_partial_update(self, **kwargs) -> Response:
        """api_asset_class_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/asset-class/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_destroy(self, **kwargs) -> Response:
        """api_asset_class_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/asset-class/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/asset-class/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_object_retrieve(self, **kwargs) -> Response:
        """api_asset_class_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/asset-class/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/asset-class/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_asset_class_tree_retrieve(self, **kwargs) -> Response:
        """api_asset_class_tree_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/asset-class/tree/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/assets/",
            path_params=[],
            query_params=[
                "applied_controls",
                "asset_class",
                "dora_criticality_assessment",
                "dora_discontinuing_impact",
                "dora_licenced_activity",
                "ebios_rm_studies",
                "exclude_children",
                "exclude_parents",
                "filtering_labels",
                "folder",
                "id",
                "is_business_function",
                "limit",
                "name",
                "offset",
                "ordering",
                "organisation_objectives",
                "parent_assets",
                "personal_data",
                "risk_scenarios",
                "search",
                "security_exceptions",
                "type",
                "vulnerabilities",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_assets_create(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/assets/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_retrieve(self, **kwargs) -> Response:
        """Populate `optimized_data` for the single retrieved asset so the"""
        return self._call(
            http="GET",
            url_template="/api/assets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_update(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/assets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/assets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_destroy(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/assets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/assets/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_asset_class_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/asset_class/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_autocomplete_retrieve(self, **kwargs) -> Response:
        """Minimal endpoint for autocomplete selects — skips graph traversal."""
        return self._call(
            http="GET",
            url_template="/api/assets/autocomplete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/assets/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_batch_create_create(self, **kwargs) -> Response:
        """Batch create multiple assets from a text list with parent-child relationships."""
        return self._call(
            http="POST",
            url_template="/api/assets/batch-create/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_disaster_recovery_objectives_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/disaster_recovery_objectives/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_dora_criticality_assessment_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/dora_criticality_assessment/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_dora_discontinuing_impact_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/dora_discontinuing_impact/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_dora_licenced_activity_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/dora_licenced_activity/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_export_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/export_csv/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_export_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/export_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_graph_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/graph/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_ids_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/ids/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_security_objectives_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/security_objectives/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_assets_type_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows assets to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/assets/type/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
