#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantFrameworksLibraries(CisoAssistantApiBase):
    def api_filtering_labels_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/filtering-labels/",
            path_params=[],
            query_params=["folder", "id", "limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_filtering_labels_create(self, **kwargs) -> Response:
        """API endpoint that allows labels to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/filtering-labels/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_update(self, **kwargs) -> Response:
        """API endpoint that allows labels to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows labels to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_destroy(self, **kwargs) -> Response:
        """API endpoint that allows labels to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/filtering-labels/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows labels to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/filtering-labels/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_filtering_labels_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/filtering-labels/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/",
            path_params=[],
            query_params=[
                "baseline",
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_frameworks_create(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_update(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/frameworks/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/frameworks/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_destroy(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/frameworks/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_discard_draft_create(self, **kwargs) -> Response:
        """Discard editing_draft without affecting relational data."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/{id}/discard-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_duplicate_create(self, **kwargs) -> Response:
        """Deep-clone a framework with all requirement nodes, questions, and choices."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/{id}/duplicate/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_excel_template_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/excel_template/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_export_yaml_retrieve(self, **kwargs) -> Response:
        """Export a framework as a library-compatible YAML file."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/export-yaml/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_mapping_stats_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/mapping_stats/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_mappings_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/mappings/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_publish_draft_create(self, **kwargs) -> Response:
        """Publish editing_draft → relational DB, snapshot history, bump version."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/{id}/publish-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_publish_draft_preview_create(self, **kwargs) -> Response:
        """Preview the impact of publishing the current draft."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/{id}/publish-draft-preview/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_report_retrieve(self, **kwargs) -> Response:
        """Cross-assessment report for one framework."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/report/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_save_draft_partial_update(self, **kwargs) -> Response:
        """Update editing_draft with the current WIP from the frontend."""
        return self._call(
            http="PATCH",
            url_template="/api/frameworks/{id}/save-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_serve_image_retrieve(self, **kwargs) -> Response:
        """Serve an image attachment belonging to this framework."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/serve-image/{attachment_id}/",
            path_params=["attachment_id", "id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_start_editing_create(self, **kwargs) -> Response:
        """Serialize the framework tree into editing_draft to begin editing."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/{id}/start-editing/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_tree_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/{id}/tree/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_upload_image_create(self, **kwargs) -> Response:
        """Upload an image to this framework (for splash screen markdown in draft mode)."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/{id}/upload-image/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/frameworks/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_names_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/names/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_provider_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_frameworks_used_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows frameworks to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/frameworks/used/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/library-filtering-labels/",
            path_params=[],
            query_params=["folder", "id", "limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_create(self, **kwargs) -> Response:
        """API endpoint that allows library labels to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/library-filtering-labels/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/library-filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_update(self, **kwargs) -> Response:
        """API endpoint that allows library labels to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/library-filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows library labels to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/library-filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_destroy(self, **kwargs) -> Response:
        """API endpoint that allows library labels to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/library-filtering-labels/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/library-filtering-labels/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows library labels to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/library-filtering-labels/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_library_filtering_labels_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/library-filtering-labels/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/",
            path_params=[],
            query_params=[
                "has_update",
                "id",
                "limit",
                "locale",
                "object_type",
                "offset",
                "ordering",
                "packager",
                "provider",
                "search",
                "urn",
                "version",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_loaded_libraries_create(self, **kwargs) -> Response:
        """api_loaded_libraries_create"""
        return self._call(
            http="POST",
            url_template="/api/loaded-libraries/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_update(self, **kwargs) -> Response:
        """api_loaded_libraries_update"""
        return self._call(
            http="PUT",
            url_template="/api/loaded-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_partial_update(self, **kwargs) -> Response:
        """api_loaded_libraries_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/loaded-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_destroy(self, **kwargs) -> Response:
        """api_loaded_libraries_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/loaded-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_content_retrieve(self, **kwargs) -> Response:
        """api_loaded_libraries_content_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/{id}/content/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_object_retrieve(self, **kwargs) -> Response:
        """api_loaded_libraries_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_tree_retrieve(self, **kwargs) -> Response:
        """api_loaded_libraries_tree_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/{id}/tree/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_update_retrieve(self, **kwargs) -> Response:
        """api_loaded_libraries_update_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/{id}/update/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_available_updates_retrieve(self, **kwargs) -> Response:
        """api_loaded_libraries_available_updates_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/loaded-libraries/available-updates/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_loaded_libraries_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/loaded-libraries/batch-action/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/presets/",
            path_params=[],
            query_params=[
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_presets_create(self, **kwargs) -> Response:
        """api_presets_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/presets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_update(self, **kwargs) -> Response:
        """api_presets_update"""
        return self._call(
            http="PUT",
            url_template="/api/presets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_partial_update(self, **kwargs) -> Response:
        """api_presets_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/presets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_destroy(self, **kwargs) -> Response:
        """api_presets_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/presets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_apply_create(self, **kwargs) -> Response:
        """api_presets_apply_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/{id}/apply/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/presets/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_discard_draft_create(self, **kwargs) -> Response:
        """api_presets_discard_draft_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/{id}/discard-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_duplicate_create(self, **kwargs) -> Response:
        """api_presets_duplicate_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/{id}/duplicate/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_object_retrieve(self, **kwargs) -> Response:
        """api_presets_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/presets/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_publish_draft_create(self, **kwargs) -> Response:
        """api_presets_publish_draft_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/{id}/publish-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_publish_draft_preview_create(self, **kwargs) -> Response:
        """api_presets_publish_draft_preview_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/{id}/publish-draft-preview/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_save_draft_partial_update(self, **kwargs) -> Response:
        """api_presets_save_draft_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/presets/{id}/save-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_start_editing_create(self, **kwargs) -> Response:
        """api_presets_start_editing_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/{id}/start-editing/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/presets/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_presets_create_blank_create(self, **kwargs) -> Response:
        """api_presets_create_blank_create"""
        return self._call(
            http="POST",
            url_template="/api/presets/create-blank/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/",
            path_params=[],
            query_params=[
                "filtering_labels",
                "id",
                "is_custom",
                "is_loaded",
                "is_preset",
                "is_update",
                "limit",
                "locale",
                "object_type",
                "offset",
                "ordering",
                "packager",
                "provider",
                "search",
                "urn",
                "version",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_stored_libraries_create(self, **kwargs) -> Response:
        """api_stored_libraries_create"""
        return self._call(
            http="POST",
            url_template="/api/stored-libraries/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_update(self, **kwargs) -> Response:
        """api_stored_libraries_update"""
        return self._call(
            http="PUT",
            url_template="/api/stored-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_partial_update(self, **kwargs) -> Response:
        """api_stored_libraries_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/stored-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_destroy(self, **kwargs) -> Response:
        """api_stored_libraries_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/stored-libraries/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_content_retrieve(self, **kwargs) -> Response:
        """api_stored_libraries_content_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/{id}/content/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_import_create(self, **kwargs) -> Response:
        """api_stored_libraries_import_create"""
        return self._call(
            http="POST",
            url_template="/api/stored-libraries/{id}/import/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_object_retrieve(self, **kwargs) -> Response:
        """api_stored_libraries_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_tree_retrieve(self, **kwargs) -> Response:
        """api_stored_libraries_tree_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/{id}/tree/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_unload_create(self, **kwargs) -> Response:
        """api_stored_libraries_unload_create"""
        return self._call(
            http="POST",
            url_template="/api/stored-libraries/{id}/unload/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/stored-libraries/batch-action/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_locale_retrieve(self, **kwargs) -> Response:
        """api_stored_libraries_locale_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/locale/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_object_type_retrieve(self, **kwargs) -> Response:
        """api_stored_libraries_object_type_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/object_type/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_provider_retrieve(self, **kwargs) -> Response:
        """api_stored_libraries_provider_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/stored-libraries/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_stored_libraries_upload_create(self, **kwargs) -> Response:
        """api_stored_libraries_upload_create"""
        return self._call(
            http="POST",
            url_template="/api/stored-libraries/upload/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/terminologies/",
            path_params=[],
            query_params=[
                "builtin",
                "field_path",
                "folder",
                "id",
                "is_visible",
                "limit",
                "offset",
                "ordering",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_terminologies_create(self, **kwargs) -> Response:
        """api_terminologies_create"""
        return self._call(
            http="POST",
            url_template="/api/terminologies/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/terminologies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_update(self, **kwargs) -> Response:
        """api_terminologies_update"""
        return self._call(
            http="PUT",
            url_template="/api/terminologies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_partial_update(self, **kwargs) -> Response:
        """api_terminologies_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/terminologies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_destroy(self, **kwargs) -> Response:
        """api_terminologies_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/terminologies/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/terminologies/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_object_retrieve(self, **kwargs) -> Response:
        """api_terminologies_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/terminologies/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/terminologies/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_terminologies_field_path_retrieve(self, **kwargs) -> Response:
        """api_terminologies_field_path_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/terminologies/field_path/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
