#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantSecurityFindings(CisoAssistantApiBase):
    def api_findings_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/findings/",
            path_params=[],
            query_params=[
                "applied_controls",
                "due_date",
                "evidences",
                "filtering_labels",
                "findings_assessment",
                "folder",
                "id",
                "limit",
                "name",
                "offset",
                "ordering",
                "owner",
                "priority",
                "search",
                "severity",
                "status",
                "vulnerabilities",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_findings_create(self, **kwargs) -> Response:
        """api_findings_create"""
        return self._call(
            http="POST",
            url_template="/api/findings/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/",
            path_params=[],
            query_params=[
                "authors",
                "category",
                "evidences",
                "folder",
                "genericcollection",
                "id",
                "limit",
                "name",
                "offset",
                "ordering",
                "perimeter",
                "ref_id",
                "search",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_findings_assessments_create(self, **kwargs) -> Response:
        """api_findings_assessments_create"""
        return self._call(
            http="POST",
            url_template="/api/findings-assessments/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_update(self, **kwargs) -> Response:
        """api_findings_assessments_update"""
        return self._call(
            http="PUT",
            url_template="/api/findings-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_partial_update(self, **kwargs) -> Response:
        """api_findings_assessments_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/findings-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_destroy(self, **kwargs) -> Response:
        """api_findings_assessments_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/findings-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_md_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_md_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/md/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_metrics_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_metrics_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/metrics/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_object_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_pdf_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_pdf_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/pdf/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_xlsx_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_xlsx_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/{id}/xlsx/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/findings-assessments/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_category_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_category_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/category/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_status_retrieve(self, **kwargs) -> Response:
        """api_findings_assessments_status_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_assessments_sunburst_data_retrieve(self, **kwargs) -> Response:
        """Returns FindingsAssessment data structured for sunburst visualization:"""
        return self._call(
            http="GET",
            url_template="/api/findings-assessments/sunburst_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/findings/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_update(self, **kwargs) -> Response:
        """api_findings_update"""
        return self._call(
            http="PUT",
            url_template="/api/findings/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_partial_update(self, **kwargs) -> Response:
        """api_findings_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/findings/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_destroy(self, **kwargs) -> Response:
        """api_findings_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/findings/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/findings/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_object_retrieve(self, **kwargs) -> Response:
        """api_findings_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/findings/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_owner_retrieve(self, **kwargs) -> Response:
        """api_findings_owner_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings/owner/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_priority_retrieve(self, **kwargs) -> Response:
        """api_findings_priority_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings/priority/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_sankey_data_retrieve(self, **kwargs) -> Response:
        """Returns findings data structured for Sankey diagram:"""
        return self._call(
            http="GET",
            url_template="/api/findings/sankey_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_severity_retrieve(self, **kwargs) -> Response:
        """api_findings_severity_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings/severity/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_findings_status_retrieve(self, **kwargs) -> Response:
        """api_findings_status_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/findings/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/security-advisories/",
            path_params=[],
            query_params=[
                "filtering_labels",
                "folder",
                "id",
                "library",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
                "source",
                "urn",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_security_advisories_create(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/security-advisories/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/security-advisories/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_update(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/security-advisories/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/security-advisories/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_destroy(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/security-advisories/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/security-advisories/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_enrich_create(self, **kwargs) -> Response:
        """Enrich this advisory with data from its source (NVD or EUVD)."""
        return self._call(
            http="POST",
            url_template="/api/security-advisories/{id}/enrich/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-advisories/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_autocomplete_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-advisories/autocomplete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/security-advisories/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_source_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security advisories to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-advisories/source/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_sync_euvd_create(self, **kwargs) -> Response:
        """Sync EUVD exploited vulnerabilities synchronously."""
        return self._call(
            http="POST",
            url_template="/api/security-advisories/sync-euvd/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_advisories_sync_kev_create(self, **kwargs) -> Response:
        """Sync KEV feed synchronously. Scheduled async via Huey periodic tasks."""
        return self._call(
            http="POST",
            url_template="/api/security-advisories/sync-kev/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/",
            path_params=[],
            query_params=[
                "approver",
                "expiration_date",
                "folder",
                "genericcollection",
                "id",
                "limit",
                "name",
                "offset",
                "ordering",
                "owners",
                "requirement_assessments",
                "risk_scenarios",
                "search",
                "severity",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_security_exceptions_create(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/security-exceptions/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_update(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/security-exceptions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/security-exceptions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_destroy(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/security-exceptions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/security-exceptions/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_export_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/export_csv/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_export_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/export_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_sankey_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/sankey_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_severity_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/severity/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_security_exceptions_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows security exceptions to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/security-exceptions/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
