#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantRiskManagement(CisoAssistantApiBase):
    def api_cwes_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/cwes/",
            path_params=[],
            query_params=[
                "filtering_labels",
                "folder",
                "id",
                "library",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
                "urn",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_cwes_create(self, **kwargs) -> Response:
        """API endpoint that allows CWEs to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/cwes/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/cwes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_update(self, **kwargs) -> Response:
        """API endpoint that allows CWEs to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/cwes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows CWEs to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/cwes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_destroy(self, **kwargs) -> Response:
        """API endpoint that allows CWEs to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/cwes/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/cwes/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows CWEs to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/cwes/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_autocomplete_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows CWEs to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/cwes/autocomplete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/cwes/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_cwes_sync_catalog_create(self, **kwargs) -> Response:
        """Sync CWE catalog from MITRE."""
        return self._call(
            http="POST",
            url_template="/api/cwes/sync-catalog/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/",
            path_params=[],
            query_params=[
                "approver",
                "expiry_date",
                "expiry_date__gt",
                "expiry_date__gte",
                "expiry_date__lt",
                "expiry_date__lte",
                "expiry_date__month",
                "expiry_date__year",
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "risk_scenarios",
                "search",
                "state",
                "to_review",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_risk_acceptances_create(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_update(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/risk-acceptances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/risk-acceptances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_destroy(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/risk-acceptances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_accept_create(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/{id}/accept/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_draft_create(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/{id}/draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_reject_create(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/{id}/reject/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_revoke_create(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/{id}/revoke/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_submit_create(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/{id}/submit/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/risk-acceptances/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_state_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/state/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_to_review_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/to_review/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_acceptances_waiting_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk acceptance to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-acceptances/waiting/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/",
            path_params=[],
            query_params=[
                "authors",
                "due_date",
                "due_date__month",
                "due_date__year",
                "ebios_rm_study",
                "folder",
                "genericcollection",
                "id",
                "limit",
                "name",
                "offset",
                "ordering",
                "perimeter",
                "ref_id",
                "reviewers",
                "risk_matrix",
                "search",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_risk_assessments_create(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-assessments/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_update(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/risk-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/risk-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_destroy(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/risk-assessments/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_action_plan_list(self, **kwargs) -> Response:
        """api_risk_assessments_action_plan_list"""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/action-plan/",
            path_params=["id"],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_risk_assessments_action_plan_budget_overview_list(
        self, **kwargs
    ) -> Response:
        """Mixin that computes budget aggregation over an applied controls queryset."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/action-plan/budget-overview/",
            path_params=["id"],
            query_params=["limit", "offset", "ordering", "search"],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_risk_assessments_action_plan_excel_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/action_plan_excel/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_action_plan_pdf_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/action_plan_pdf/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_convert_to_quantitative_create(self, **kwargs) -> Response:
        """Convert a qualitative risk assessment to a quantitative risk study."""
        return self._call(
            http="POST",
            url_template="/api/risk-assessments/{id}/convert_to_quantitative/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_duplicate_create(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-assessments/{id}/duplicate/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_quality_check_retrieve_2(self, **kwargs) -> Response:
        """Returns the quality check of the risk_assessment"""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/quality_check/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_risk_analytics_retrieve(self, **kwargs) -> Response:
        """Analytics data for a single risk assessment."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/risk_analytics/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_risk_assessment_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/risk_assessment_csv/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_risk_assessment_pdf_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/risk_assessment_pdf/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_risk_assessment_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/risk_assessment_xlsx/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_risk_timeline_retrieve(self, **kwargs) -> Response:
        """Returns risk metrics over time from BuiltinMetricSample snapshots."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/risk_timeline/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_sync_to_actions_create(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-assessments/{id}/sync-to-actions/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_sync_from_ebios_rm_create(self, **kwargs) -> Response:
        """Synchronize an existing risk assessment with its linked EBIOS RM study."""
        return self._call(
            http="POST",
            url_template="/api/risk-assessments/{id}/sync_from_ebios_rm/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_sync_preview_retrieve(self, **kwargs) -> Response:
        """Preview what a sync from EBIOS RM would produce."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/{id}/sync_preview/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/risk-assessments/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_per_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/per_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_quality_check_retrieve(self, **kwargs) -> Response:
        """Returns the quality check of the risk assessments"""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/quality_check/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_assessments_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk assessments to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-assessments/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/",
            path_params=[],
            query_params=[
                "folder",
                "id",
                "is_enabled",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_risk_matrices_create(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_update(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/risk-matrices/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/risk-matrices/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_destroy(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/risk-matrices/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_create_draft_from_create(self, **kwargs) -> Response:
        """Clone an existing matrix into a new unpublished RiskMatrix with editing_draft."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/{id}/create-draft-from/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_discard_draft_create(self, **kwargs) -> Response:
        """Discard editing_draft without affecting json_definition."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/{id}/discard-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_export_yaml_retrieve(self, **kwargs) -> Response:
        """Export a matrix as a library-compatible YAML file."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/{id}/export-yaml/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_publish_draft_create(self, **kwargs) -> Response:
        """Publish editing_draft → json_definition, snapshot history, bump version."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/{id}/publish-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_save_draft_partial_update(self, **kwargs) -> Response:
        """Update editing_draft with current WIP. Metadata stays draft-scoped until publish."""
        return self._call(
            http="PATCH",
            url_template="/api/risk-matrices/{id}/save-draft/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_start_editing_create(self, **kwargs) -> Response:
        """Copy json_definition into editing_draft to begin editing."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/{id}/start-editing/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_colors_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/colors/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_create_draft_create(self, **kwargs) -> Response:
        """Create a new unpublished RiskMatrix with an editing_draft for the visual editor."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/create-draft/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_ids_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/ids/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_impact_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/impact/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_import_yaml_create(self, **kwargs) -> Response:
        """Import a library YAML file and create a new draft matrix from it."""
        return self._call(
            http="POST",
            url_template="/api/risk-matrices/import-yaml/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_probability_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/probability/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_provider_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_risk_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/risk/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_matrices_used_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk matrices to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-matrices/used/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/",
            path_params=[],
            query_params=[
                "applied_controls",
                "assets",
                "current_impact",
                "current_level",
                "current_proba",
                "exclude",
                "existing_applied_controls",
                "filtering_labels",
                "folder",
                "id",
                "incidents",
                "limit",
                "name",
                "offset",
                "ordering",
                "owner",
                "perimeter",
                "qualifications",
                "residual_impact",
                "residual_level",
                "residual_proba",
                "risk_assessment",
                "search",
                "security_exceptions",
                "threats",
                "treatment",
                "vulnerabilities",
                "within_tolerance",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_risk_scenarios_create(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-scenarios/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_update(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/risk-scenarios/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/risk-scenarios/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_destroy(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/risk-scenarios/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_impact_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/{id}/impact/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_probability_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/{id}/probability/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_strength_of_knowledge_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/{id}/strength_of_knowledge/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_sync_to_actions_create(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/risk-scenarios/{id}/sync-to-actions/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/risk-scenarios/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_count_per_level_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/count_per_level/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_default_ref_id_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/default_ref_id/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_export_csv_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/export_csv/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_export_xlsx_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/export_xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_per_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/per_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_qualifications_count_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/qualifications_count/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_risk_scenarios_treatment_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows risk scenarios to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/risk-scenarios/treatment/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/threats/",
            path_params=[],
            query_params=[
                "filtering_labels",
                "findings",
                "folder",
                "id",
                "library",
                "limit",
                "offset",
                "ordering",
                "provider",
                "risk_scenarios",
                "search",
                "urn",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_threats_create(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/threats/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/threats/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_update(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/threats/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/threats/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_destroy(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/threats/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/threats/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/threats/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/threats/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_ids_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/threats/ids/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_provider_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/threats/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_threats_threats_count_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows threats to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/threats/threats_count/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/",
            path_params=[],
            query_params=[
                "applied_controls",
                "assets",
                "cwes",
                "filtering_labels",
                "findings",
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "risk_scenarios",
                "search",
                "security_advisories",
                "security_exceptions",
                "severity",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_vulnerabilities_create(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="POST",
            url_template="/api/vulnerabilities/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_update(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="PUT",
            url_template="/api/vulnerabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_partial_update(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="PATCH",
            url_template="/api/vulnerabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_destroy(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="DELETE",
            url_template="/api/vulnerabilities/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_object_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_autocomplete_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/autocomplete/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/vulnerabilities/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_refresh_due_dates_create(self, **kwargs) -> Response:
        """Recalculate due_date for all vulnerabilities based on current SLA policy."""
        return self._call(
            http="POST",
            url_template="/api/vulnerabilities/refresh-due-dates/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_sankey_data_retrieve(self, **kwargs) -> Response:
        """Returns vulnerability data structured for Sankey diagram:"""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/sankey_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_severity_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/severity/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that allows vulnerabilities to be viewed or edited."""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_vulnerabilities_treemap_data_retrieve(self, **kwargs) -> Response:
        """Returns vulnerability data structured for treemap visualization:"""
        return self._call(
            http="GET",
            url_template="/api/vulnerabilities/treemap_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
