#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_base import CisoAssistantApiBase
from ciso_assistant_api.ciso_assistant_models import Response


class CisoAssistantAnalyticsMetrology(CisoAssistantApiBase):
    def api_agg_data_retrieve(self, **kwargs) -> Response:
        """api_agg_data_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/agg_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_analytics_export_xlsx_retrieve(self, **kwargs) -> Response:
        """Export all analytics dashboard data as a multi-sheet XLSX file."""
        return self._call(
            http="GET",
            url_template="/api/analytics/export/xlsx/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_composer_data_retrieve(self, **kwargs) -> Response:
        """api_composer_data_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/composer_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_get_audits_metrics_retrieve(self, **kwargs) -> Response:
        """API endpoint that returns the expensive audit metrics (progress avg + audits stats)."""
        return self._call(
            http="GET",
            url_template="/api/get_audits_metrics/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_get_combined_assessments_status_retrieve(self, **kwargs) -> Response:
        """API endpoint that returns combined assessment counts per status"""
        return self._call(
            http="GET",
            url_template="/api/get_combined_assessments_status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_get_counters_retrieve(self, **kwargs) -> Response:
        """API endpoint that returns the counters"""
        return self._call(
            http="GET",
            url_template="/api/get_counters/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_get_governance_calendar_data_retrieve(self, **kwargs) -> Response:
        """API endpoint that returns governance activity calendar data"""
        return self._call(
            http="GET",
            url_template="/api/get_governance_calendar_data/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_get_metrics_retrieve(self, **kwargs) -> Response:
        """API endpoint that returns the counters"""
        return self._call(
            http="GET",
            url_template="/api/get_metrics/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/metrology/builtin-metric-samples/",
            path_params=[],
            query_params=[
                "content_type",
                "date",
                "id",
                "limit",
                "object_id",
                "offset",
                "ordering",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_create(self, **kwargs) -> Response:
        """api_metrology_builtin_metric_samples_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/builtin-metric-samples/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/metrology/builtin-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_update(self, **kwargs) -> Response:
        """api_metrology_builtin_metric_samples_update"""
        return self._call(
            http="PUT",
            url_template="/api/metrology/builtin-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_partial_update(self, **kwargs) -> Response:
        """api_metrology_builtin_metric_samples_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/metrology/builtin-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_destroy(self, **kwargs) -> Response:
        """api_metrology_builtin_metric_samples_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/metrology/builtin-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_cascade_info_retrieve(
        self, **kwargs
    ) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/metrology/builtin-metric-samples/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_object_retrieve(
        self, **kwargs
    ) -> Response:
        """api_metrology_builtin_metric_samples_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/builtin-metric-samples/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_batch_action_create(
        self, **kwargs
    ) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/metrology/builtin-metric-samples/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_for_object_retrieve(
        self, **kwargs
    ) -> Response:
        """api_metrology_builtin_metric_samples_for_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/builtin-metric-samples/for_object/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_refresh_create(self, **kwargs) -> Response:
        """api_metrology_builtin_metric_samples_refresh_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/builtin-metric-samples/refresh/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_builtin_metric_samples_supported_models_retrieve(
        self, **kwargs
    ) -> Response:
        """api_metrology_builtin_metric_samples_supported_models_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/builtin-metric-samples/supported_models/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/metrology/custom-metric-samples/",
            path_params=[],
            query_params=[
                "evidence_revision",
                "folder",
                "id",
                "limit",
                "metric_instance",
                "offset",
                "ordering",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_create(self, **kwargs) -> Response:
        """api_metrology_custom_metric_samples_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/custom-metric-samples/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/metrology/custom-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_update(self, **kwargs) -> Response:
        """api_metrology_custom_metric_samples_update"""
        return self._call(
            http="PUT",
            url_template="/api/metrology/custom-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_partial_update(self, **kwargs) -> Response:
        """api_metrology_custom_metric_samples_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/metrology/custom-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_destroy(self, **kwargs) -> Response:
        """api_metrology_custom_metric_samples_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/metrology/custom-metric-samples/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_cascade_info_retrieve(
        self, **kwargs
    ) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/metrology/custom-metric-samples/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_object_retrieve(self, **kwargs) -> Response:
        """api_metrology_custom_metric_samples_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/custom-metric-samples/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_custom_metric_samples_batch_action_create(
        self, **kwargs
    ) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/metrology/custom-metric-samples/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/",
            path_params=[],
            query_params=[
                "aggregation",
                "chart_type",
                "dashboard",
                "folder",
                "id",
                "limit",
                "metric_instance",
                "offset",
                "ordering",
                "search",
                "time_range",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_create(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/dashboard-widgets/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_update(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_update"""
        return self._call(
            http="PUT",
            url_template="/api/metrology/dashboard-widgets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_partial_update(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/metrology/dashboard-widgets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_destroy(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/metrology/dashboard-widgets/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_cascade_info_retrieve(
        self, **kwargs
    ) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_object_retrieve(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_aggregation_retrieve(
        self, **kwargs
    ) -> Response:
        """api_metrology_dashboard_widgets_aggregation_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/aggregation/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/metrology/dashboard-widgets/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_chart_type_retrieve(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_chart_type_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/chart_type/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboard_widgets_time_range_retrieve(self, **kwargs) -> Response:
        """api_metrology_dashboard_widgets_time_range_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboard-widgets/time_range/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboards/",
            path_params=[],
            query_params=[
                "filtering_labels",
                "folder",
                "id",
                "limit",
                "offset",
                "ordering",
                "search",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_create(self, **kwargs) -> Response:
        """api_metrology_dashboards_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/dashboards/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboards/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_update(self, **kwargs) -> Response:
        """api_metrology_dashboards_update"""
        return self._call(
            http="PUT",
            url_template="/api/metrology/dashboards/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_partial_update(self, **kwargs) -> Response:
        """api_metrology_dashboards_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/metrology/dashboards/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_destroy(self, **kwargs) -> Response:
        """api_metrology_dashboards_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/metrology/dashboards/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_cascade_info_retrieve(self, **kwargs) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboards/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_object_retrieve(self, **kwargs) -> Response:
        """api_metrology_dashboards_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/dashboards/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_dashboards_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/metrology/dashboards/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-definitions/",
            path_params=[],
            query_params=[
                "category",
                "filtering_labels",
                "folder",
                "id",
                "is_published",
                "library",
                "limit",
                "offset",
                "ordering",
                "provider",
                "search",
                "unit",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_create(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/metric-definitions/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-definitions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_update(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_update"""
        return self._call(
            http="PUT",
            url_template="/api/metrology/metric-definitions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_partial_update(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/metrology/metric-definitions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_destroy(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/metrology/metric-definitions/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_cascade_info_retrieve(
        self, **kwargs
    ) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-definitions/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_object_retrieve(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-definitions/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_batch_action_create(
        self, **kwargs
    ) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/metrology/metric-definitions/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_category_retrieve(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_category_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-definitions/category/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_definitions_provider_retrieve(self, **kwargs) -> Response:
        """api_metrology_metric_definitions_provider_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-definitions/provider/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_list(self, **kwargs) -> Response:
        """Override the list method to inject optimized data into the serializer context."""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-instances/",
            path_params=[],
            query_params=[
                "collection_frequency",
                "evidences",
                "filtering_labels",
                "folder",
                "id",
                "limit",
                "metric_definition",
                "offset",
                "ordering",
                "organisation_objectives",
                "owner",
                "search",
                "status",
            ],
            has_body=False,
            paginate="page",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_create(self, **kwargs) -> Response:
        """api_metrology_metric_instances_create"""
        return self._call(
            http="POST",
            url_template="/api/metrology/metric-instances/",
            path_params=[],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_retrieve(self, **kwargs) -> Response:
        """Return a single object with unauthorized related fields masked."""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-instances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_update(self, **kwargs) -> Response:
        """api_metrology_metric_instances_update"""
        return self._call(
            http="PUT",
            url_template="/api/metrology/metric-instances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_partial_update(self, **kwargs) -> Response:
        """api_metrology_metric_instances_partial_update"""
        return self._call(
            http="PATCH",
            url_template="/api/metrology/metric-instances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=True,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_destroy(self, **kwargs) -> Response:
        """api_metrology_metric_instances_destroy"""
        return self._call(
            http="DELETE",
            url_template="/api/metrology/metric-instances/{id}/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_cascade_info_retrieve(
        self, **kwargs
    ) -> Response:
        """Cascade preview:"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-instances/{id}/cascade-info/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_object_retrieve(self, **kwargs) -> Response:
        """api_metrology_metric_instances_object_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-instances/{id}/object/",
            path_params=["id"],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_batch_action_create(self, **kwargs) -> Response:
        """Perform a batch action on multiple objects."""
        return self._call(
            http="POST",
            url_template="/api/metrology/metric-instances/batch-action/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_collection_frequency_retrieve(
        self, **kwargs
    ) -> Response:
        """api_metrology_metric_instances_collection_frequency_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-instances/collection_frequency/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )

    def api_metrology_metric_instances_status_retrieve(self, **kwargs) -> Response:
        """api_metrology_metric_instances_status_retrieve"""
        return self._call(
            http="GET",
            url_template="/api/metrology/metric-instances/status/",
            path_params=[],
            query_params=[],
            has_body=False,
            paginate="none",
            kwargs=kwargs,
        )
