"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from typing import Any

from fastmcp import Context, FastMCP
from fastmcp.dependencies import Depends
from pydantic import Field

from ciso_assistant_api.auth import get_client


def register_assets_tools(mcp: FastMCP):
    @mcp.tool(tags={"assets"})
    async def ciso_assistant_assets(
        action: str = Field(
            description="Action to perform. One of: 'api_asset_capabilities_list', 'api_asset_capabilities_create', 'api_asset_capabilities_retrieve', 'api_asset_capabilities_update', 'api_asset_capabilities_partial_update', 'api_asset_capabilities_destroy', 'api_asset_capabilities_cascade_info_retrieve', 'api_asset_capabilities_object_retrieve', 'api_asset_capabilities_batch_action_create', 'api_asset_class_list', 'api_asset_class_create', 'api_asset_class_retrieve', 'api_asset_class_update', 'api_asset_class_partial_update', 'api_asset_class_destroy', 'api_asset_class_cascade_info_retrieve', 'api_asset_class_object_retrieve', 'api_asset_class_batch_action_create', 'api_asset_class_tree_retrieve', 'api_assets_list', 'api_assets_create', 'api_assets_retrieve', 'api_assets_update', 'api_assets_partial_update', 'api_assets_destroy', 'api_assets_cascade_info_retrieve', 'api_assets_object_retrieve', 'api_assets_asset_class_retrieve', 'api_assets_autocomplete_retrieve', 'api_assets_batch_action_create', 'api_assets_batch_create_create', 'api_assets_disaster_recovery_objectives_retrieve', 'api_assets_dora_criticality_assessment_retrieve', 'api_assets_dora_discontinuing_impact_retrieve', 'api_assets_dora_licenced_activity_retrieve', 'api_assets_export_csv_retrieve', 'api_assets_export_xlsx_retrieve', 'api_assets_graph_retrieve', 'api_assets_ids_retrieve', 'api_assets_security_objectives_retrieve', 'api_assets_type_retrieve'"
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters (path, query, and body fields) for the action.",
        ),
        client=Depends(get_client),
        ctx: Context | None = Field(
            default=None, description="MCP context for progress reporting"
        ),
    ) -> Any:
        """Manage CISO Assistant assets operations."""
        if ctx:
            await ctx.info(f"Executing ciso_assistant_assets action: {action}")
        import json

        try:
            kwargs = json.loads(params_json) if params_json else {}
        except Exception as e:
            return {"error": f"Invalid params_json: {e}"}
        if not isinstance(kwargs, dict):
            return {"error": "params_json must decode to a JSON object"}
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        if action == "api_asset_capabilities_list":
            return client.api_asset_capabilities_list(**kwargs)
        elif action == "api_asset_capabilities_create":
            return client.api_asset_capabilities_create(**kwargs)
        elif action == "api_asset_capabilities_retrieve":
            return client.api_asset_capabilities_retrieve(**kwargs)
        elif action == "api_asset_capabilities_update":
            return client.api_asset_capabilities_update(**kwargs)
        elif action == "api_asset_capabilities_partial_update":
            return client.api_asset_capabilities_partial_update(**kwargs)
        elif action == "api_asset_capabilities_destroy":
            return client.api_asset_capabilities_destroy(**kwargs)
        elif action == "api_asset_capabilities_cascade_info_retrieve":
            return client.api_asset_capabilities_cascade_info_retrieve(**kwargs)
        elif action == "api_asset_capabilities_object_retrieve":
            return client.api_asset_capabilities_object_retrieve(**kwargs)
        elif action == "api_asset_capabilities_batch_action_create":
            return client.api_asset_capabilities_batch_action_create(**kwargs)
        elif action == "api_asset_class_list":
            return client.api_asset_class_list(**kwargs)
        elif action == "api_asset_class_create":
            return client.api_asset_class_create(**kwargs)
        elif action == "api_asset_class_retrieve":
            return client.api_asset_class_retrieve(**kwargs)
        elif action == "api_asset_class_update":
            return client.api_asset_class_update(**kwargs)
        elif action == "api_asset_class_partial_update":
            return client.api_asset_class_partial_update(**kwargs)
        elif action == "api_asset_class_destroy":
            return client.api_asset_class_destroy(**kwargs)
        elif action == "api_asset_class_cascade_info_retrieve":
            return client.api_asset_class_cascade_info_retrieve(**kwargs)
        elif action == "api_asset_class_object_retrieve":
            return client.api_asset_class_object_retrieve(**kwargs)
        elif action == "api_asset_class_batch_action_create":
            return client.api_asset_class_batch_action_create(**kwargs)
        elif action == "api_asset_class_tree_retrieve":
            return client.api_asset_class_tree_retrieve(**kwargs)
        elif action == "api_assets_list":
            return client.api_assets_list(**kwargs)
        elif action == "api_assets_create":
            return client.api_assets_create(**kwargs)
        elif action == "api_assets_retrieve":
            return client.api_assets_retrieve(**kwargs)
        elif action == "api_assets_update":
            return client.api_assets_update(**kwargs)
        elif action == "api_assets_partial_update":
            return client.api_assets_partial_update(**kwargs)
        elif action == "api_assets_destroy":
            return client.api_assets_destroy(**kwargs)
        elif action == "api_assets_cascade_info_retrieve":
            return client.api_assets_cascade_info_retrieve(**kwargs)
        elif action == "api_assets_object_retrieve":
            return client.api_assets_object_retrieve(**kwargs)
        elif action == "api_assets_asset_class_retrieve":
            return client.api_assets_asset_class_retrieve(**kwargs)
        elif action == "api_assets_autocomplete_retrieve":
            return client.api_assets_autocomplete_retrieve(**kwargs)
        elif action == "api_assets_batch_action_create":
            return client.api_assets_batch_action_create(**kwargs)
        elif action == "api_assets_batch_create_create":
            return client.api_assets_batch_create_create(**kwargs)
        elif action == "api_assets_disaster_recovery_objectives_retrieve":
            return client.api_assets_disaster_recovery_objectives_retrieve(**kwargs)
        elif action == "api_assets_dora_criticality_assessment_retrieve":
            return client.api_assets_dora_criticality_assessment_retrieve(**kwargs)
        elif action == "api_assets_dora_discontinuing_impact_retrieve":
            return client.api_assets_dora_discontinuing_impact_retrieve(**kwargs)
        elif action == "api_assets_dora_licenced_activity_retrieve":
            return client.api_assets_dora_licenced_activity_retrieve(**kwargs)
        elif action == "api_assets_export_csv_retrieve":
            return client.api_assets_export_csv_retrieve(**kwargs)
        elif action == "api_assets_export_xlsx_retrieve":
            return client.api_assets_export_xlsx_retrieve(**kwargs)
        elif action == "api_assets_graph_retrieve":
            return client.api_assets_graph_retrieve(**kwargs)
        elif action == "api_assets_ids_retrieve":
            return client.api_assets_ids_retrieve(**kwargs)
        elif action == "api_assets_security_objectives_retrieve":
            return client.api_assets_security_objectives_retrieve(**kwargs)
        elif action == "api_assets_type_retrieve":
            return client.api_assets_type_retrieve(**kwargs)
        raise ValueError(f"Unknown action: {action}")
