#!/usr/bin/python
"""Auto-generated by scripts/generate_from_openapi.py — do not edit by hand."""

from ciso_assistant_api.api.api_client_analytics_metrology import (
    CisoAssistantAnalyticsMetrology,
)
from ciso_assistant_api.api.api_client_assets import CisoAssistantAssets
from ciso_assistant_api.api.api_client_auth_users import CisoAssistantAuthUsers
from ciso_assistant_api.api.api_client_chat import CisoAssistantChat
from ciso_assistant_api.api.api_client_compliance import CisoAssistantCompliance
from ciso_assistant_api.api.api_client_crq import CisoAssistantCrq
from ciso_assistant_api.api.api_client_ebios_rm import CisoAssistantEbiosRm
from ciso_assistant_api.api.api_client_evidence import CisoAssistantEvidence
from ciso_assistant_api.api.api_client_frameworks_libraries import (
    CisoAssistantFrameworksLibraries,
)
from ciso_assistant_api.api.api_client_governance import CisoAssistantGovernance
from ciso_assistant_api.api.api_client_incidents import CisoAssistantIncidents
from ciso_assistant_api.api.api_client_integrations import CisoAssistantIntegrations
from ciso_assistant_api.api.api_client_privacy import CisoAssistantPrivacy
from ciso_assistant_api.api.api_client_resilience import CisoAssistantResilience
from ciso_assistant_api.api.api_client_risk_management import (
    CisoAssistantRiskManagement,
)
from ciso_assistant_api.api.api_client_security_findings import (
    CisoAssistantSecurityFindings,
)
from ciso_assistant_api.api.api_client_settings import CisoAssistantSettings
from ciso_assistant_api.api.api_client_tasks_timeline import CisoAssistantTasksTimeline
from ciso_assistant_api.api.api_client_third_party import CisoAssistantThirdParty


class Api(
    CisoAssistantAnalyticsMetrology,
    CisoAssistantAssets,
    CisoAssistantAuthUsers,
    CisoAssistantChat,
    CisoAssistantCompliance,
    CisoAssistantCrq,
    CisoAssistantEbiosRm,
    CisoAssistantEvidence,
    CisoAssistantFrameworksLibraries,
    CisoAssistantGovernance,
    CisoAssistantIncidents,
    CisoAssistantIntegrations,
    CisoAssistantPrivacy,
    CisoAssistantResilience,
    CisoAssistantRiskManagement,
    CisoAssistantSecurityFindings,
    CisoAssistantSettings,
    CisoAssistantTasksTimeline,
    CisoAssistantThirdParty,
):
    """Composite CISO Assistant API client — every domain client, one class."""

    __slots__ = ()
